package br.gov.agu.abakoapi.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;



@Getter
@AllArgsConstructor
public enum BeneficiosEnum {
    PENSAO_POR_MORTE_DO_TRABALHADOR_RURAL("1 - PENSÃO POR MORTE  DO TRABALHADOR RURAL"),
    APOSENTADORIA_POR_IDADE_DO_TRABALHADOR_RURAL("7 - APOSENTADORIA POR IDADE  DO TRABALHADOR RURAL"),
    PENSAO_POR_MORTE("21 - PENSÃO POR MORTE"),
    AUXILIO_RECLUSAO("25 - AUXÍLIO-RECLUSÃO"),
    AUXILIO_DOENCA("31 - AUXÍLIO-DOENÇA"),
    APOSENTADORIA_POR_INVALIDEZ("32 - APOSENTADORIA POR INVALIDEZ"),
    AUXILIO_ACIDENTE("36 - AUXÍLIO-ACIDENTE"),
    APOSENTADORIA_POR_IDADE("41 - APOSENTADORIA POR IDADE"),
    APOSENTADORIA_POR_TEMPO_DE_CONTRIBUICAO("42 - APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO"),
    APOSENTADORIA_ESPECIAL("46 - APOSENTADORIA ESPECIAL"),
    APOSENTADORIA_POR_TEMPO_DE_CONTRIBUICAO_DO_PROFESSOR("57 - APOSENTADORIA POR  TEMPO DE CONTRIBUIÇÃO DE PROFESSOR"),
    SALARIO_MATERNIDADE("80 - SALÁRIO-MATERNIDADE"),
    PENSAO_MENSAL_VITALICIA_DO_SERINGUEIRO("85 - PENSÃO MENSAL VITALÍCIA DO SERINGUEIRO"),
    PENSAO_MENSAL_VITALICIA_DO_DEPENDENTE_DO_SERINGUEIRO("86 - PENSÃO MENSAL VITALÍCIA DO DEPENDENTE DO SERINGUEIRO"),
    LOAS_DEFICIENTE("87 - LOAS DEFICIENTE"),
    LOAS_IDOSO("88 - LOAS IDOSO"),
    AUXILIO_DOENCA_ACIDENTARIO("91 - AUXÍLIO-DOENÇA ACIDENTÁRIO"),
    APOSENTADORIA_POR_INVALIDEZ_ACIDENTARIA("92 - APOSENTADORIA POR INVALIDEZ ACIDENTÁRIA"),
    PENSAO_POR_MORTE_ACIDENTARIA("93 - PENSÃO POR MORTE ACIDENTÁRIA"),
    AUXILIO_ACIDENTE_POR_ACIDENTE_DO_TRABALHO("94 - AUXÍLIO-ACIDENTE POR ACIDENTE DO TRABALHO"),
    AUXILIO_SUPLEMENTAR_POR_ACIDENTE_DO_TRABALHO("95 - AUXÍLIO SUPLEMENTAR POR ACIDENTE DO TRABALHO"),
    PENSAO_ESPECIAL_AO_PORTADOR_DE_HANSENIASE("96 - PENSÃO ESPECIAL AO PORTADOR DE HANSENÍASE"),
    SEGURO_DEFESO("SEGURO-DEFESO"),
    SEGURO_DESEMPREGO("SEGURO-DESEMPREGO");


    private String nome;
}